# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: itx2fkvyQrl9GlkyDdXKtTJMjiydTooU
            client-secret: lKrg2RPj-Kt82t1JkZ9tdsLvgbI0y_rxWrMl6DtZbp-WvBdSfyMwN4xYzpdDtFAm
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-y6i5ioy31lsld5uq.us.auth0.com/